package uz.pdp.simpletelegrambot.enums;

public enum ProductStatus {
    PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_NAME_UPDATE,PRODUCT_PRICE_UPDATE,PRODUCT_PRICE,PRODUCT_PHOTO_UPDATE,
    PRODUCT_PHOTO,PRODUCT_DELETE,PRODUCT_DELETE_UPDATE,PRODUCT_STATUS_UPDATE
}
